services:
  portainer-ce:
    image: wharf.es.net/dtnaas/portainer/portainer-ce
    container_name: portainer-ce
    restart: unless-stopped
    command: --admin-password $$2y$$05$$YPtwKQG4eZb/reXBR1P/we.I7AKfK2oJsL69CIbWyjvf8r9woedcS
    volumes:
      - portainer_data:/data
    expose:
      - 9000
    ports:
      - "[::1]:9000:9000"
    networks:
      - dtnaas

  portainer-agent:
    image: wharf.es.net/dtnaas/portainer/agent
    container_name: portainer-agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    expose:
      - 9001
    ports:
      - "[::1]:9001:9001"
    network_mode: bridge

  controller:
    image: wharf.es.net/dtnaas/controller:0.3rc1
    container_name: janus-controller
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=5000
      - DEBUG=1
      - 'BIND=::'
    volumes:
      - /etc/janus:/etc/janus
      - /opt/janus/controller/:/opt/janus
    expose:
      - 5000
    ports:
      - "[::1]:5000:5000"
    networks:
      - dtnaas

  agent:
    image: wharf.es.net/dtnaas/agent
    container_name: janus-agent
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - AGENT_BIND=0.0.0.0
      - AGENT_PORT=5050
      - AGENT_SSL=--ssl
    expose:
      - 5050
    ports:
      - "[::1]:5050:5050"
    network_mode: host

  janus-web:
    image: wharf.es.net/dtnaas/janus-web:0.3rc1
    container_name: janus-web
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - JANUS_WEB_CTRL_HOST=controller
      - CSRF_TRUSTED_ORIGINS=https://janus-sense.es.net
      - JANUS_USERNAME=admin
      - JANUS_PASSWORD=admin
      - ADMIN_ENABLED=false
      - LOCAL_LOGIN_ENABLED=false
      - OIDC_RP_CLIENT_ID=Janus-dev
      - BIND=[::]
    volumes:
      - /opt/janus/janus-web:/opt/janus-web
    expose:
      - 8001
    ports:
      - "[::1]:8001:8000"
    networks:
      - dtnaas

  nginx-prod:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - "[::1]:8000:8000"
      - "127.0.0.1:8000:8000"
    expose:
      - 8000
    volumes:
      - ./nginx/nginx-plain.conf:/etc/nginx/nginx.conf
      - /opt/janus/janus-web/webapp/static/static:/var/www/static
    networks:
      - dtnaas

volumes:
  portainer_data:
    external: true
    name: portainer_data

networks:
  dtnaas:
    enable_ipv6: true
    driver: bridge
    ipam:
      config:
        - subnet: fd00:dead:beef::/48

